import HeaderApp from "components/header-app"
import styles from "./styles.module.scss"

export default function Profile() {
    return (
        <HeaderApp>
            <div className={styles.banner}>
                <div className={styles.information}>
                    <img className={styles.avatar} src="profile.jpg" />
                    <div className={styles.data}>Hola mudno</div>
                </div>
            </div>
            <div className={styles.container}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae odio vel ex gravida dignissim. Suspendisse potenti. Suspendisse consectetur porttitor metus, vitae consectetur metus consectetur ut. Nullam tempor tincidunt dolor, id condimentum quam commodo at. Donec a nibh sed mi porta rhoncus. Phasellus gravida, nunc a dapibus sagittis, sem justo pretium nisi, a placerat quam leo vel dui. Integer neque leo, luctus sed tellus eget, tincidunt sodales ipsum.

Quisque vehicula dolor turpis, malesuada pulvinar sem bibendum vitae. Duis justo velit, vehicula id hendrerit a, rhoncus et nibh. Nunc pharetra mattis pulvinar. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc fringilla facilisis consectetur. Nunc ultricies, mauris eu venenatis gravida, odio lacus malesuada magna, eu commodo arcu velit vitae eros. Suspendisse tincidunt in nunc et vulputate. Sed metus enim, laoreet ut dignissim sed, bibendum at magna. Sed efficitur, nulla eget vulputate aliquet, sapien erat sagittis ante, vitae lacinia ipsum nisl at ligula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra vestibulum velit, eu commodo sem convallis sed. Cras cursus arcu vestibulum, commodo risus vitae, vulputate mi. Vivamus ullamcorper ac dui vitae ornare. Integer eget varius nibh. Duis tincidunt ipsum sit amet mollis pellentesque.

Praesent dictum mattis euismod. Integer dignissim non mi vitae commodo. Sed velit enim, vehicula a libero sed, accumsan volutpat nisi. Proin dignissim tellus id sem aliquet, ut ultrices metus gravida. Vivamus quis viverra arcu, nec cursus dui. Fusce maximus dui ut tortor fringilla fermentum. Morbi quis purus mattis, efficitur libero eu, lacinia odio. Suspendisse vitae nisi at ipsum vehicula tincidunt. Nullam vitae ante vel risus facilisis commodo. Morbi viverra vitae est commodo iaculis. Etiam quis nunc eget nisi laoreet consectetur at sit amet nulla. Fusce at massa non odio ullamcorper sodales. Nulla sagittis metus eu libero maximus, non sollicitudin ex finibus. Donec laoreet consequat purus, eget semper mi feugiat in. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla non massa pharetra, vehicula erat vel, iaculis velit.

Etiam aliquam elementum diam, eget euismod sem. Cras eu facilisis turpis. Nullam sit amet laoreet est. Maecenas vel purus dapibus, tempor quam id, laoreet urna. Fusce efficitur nisi ac velit mattis sodales. Donec sagittis vel tellus ac sagittis. Sed eu velit dignissim, lacinia nisl vitae, rhoncus nulla. Pellentesque vulputate, orci sed tincidunt viverra, odio tellus ullamcorper sapien, malesuada consectetur nulla justo id nisl. Proin non magna nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam dictum nec massa id vulputate. Sed non sodales sem, sodales ornare tellus.

Aliquam sagittis, ligula sed aliquet tincidunt, augue massa venenatis odio, pellentesque venenatis sem lacus non sapien. Maecenas feugiat a lectus finibus molestie. Mauris imperdiet ullamcorper quam vitae facilisis. Phasellus molestie tellus ut commodo accumsan. Proin at tristique ex. Nulla sed magna non erat laoreet convallis ac sit amet justo. Nullam sed diam tellus. Nulla condimentum justo velit, a lobortis ex ullamcorper ut.

Donec rutrum risus eget tellus convallis, a ultrices odio hendrerit. Fusce volutpat blandit elit. Maecenas commodo dui ut maximus luctus. Aenean eu ligula leo. Donec feugiat odio est, sed suscipit odio bibendum in. Donec id risus congue, rhoncus magna in, dignissim sapien. Pellentesque nisl ante, pellentesque non erat quis, vehicula tincidunt massa. Aliquam et imperdiet lacus, nec accumsan sapien. Curabitur vitae pulvinar arcu, nec facilisis nibh. Aenean et luctus nibh, sit amet iaculis metus. Aenean elit ante, varius eget tempus ac, venenatis id urna. Fusce tincidunt velit urna, at vestibulum lacus iaculis vitae.

Aliquam quis feugiat orci. Ut neque diam, ultricies eget mi nec, faucibus sollicitudin tellus. Ut maximus justo eu neque lobortis, nec scelerisque lorem scelerisque. Nunc auctor non arcu sed ullamcorper. Nunc venenatis tincidunt magna volutpat lacinia. Fusce dignissim neque sed vehicula faucibus. Phasellus rutrum ante vel auctor iaculis.

Ut non vehicula orci. Aenean scelerisque rutrum metus ac egestas. Suspendisse potenti. Integer at nibh pulvinar, venenatis arcu et, mattis orci. Nullam arcu lectus, vehicula nec elit nec, posuere elementum purus. Ut sagittis rutrum pharetra. Mauris vitae mauris a tellus porttitor vestibulum in venenatis mi. Maecenas pretium, libero sed accumsan volutpat, mauris lacus tincidunt ante, eget ultrices tellus ante in arcu. Vivamus justo tellus, egestas id gravida non, tempor eu mauris. Praesent suscipit est et metus varius, quis posuere sem malesuada.

Fusce ultrices lobortis quam, vel sollicitudin purus imperdiet vel. Mauris dignissim in leo eget venenatis. Etiam augue sem, placerat vitae nisl sed, porta scelerisque nisl. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent rhoncus, felis id tempor tristique, quam erat finibus massa, ac egestas diam est sed nunc. Sed sem tortor, vulputate nec gravida et, tristique sit amet lorem. In ultricies blandit lorem sit amet porta. Morbi pretium quis libero ac viverra. Vivamus ultrices quis felis sit amet pellentesque. Duis ultricies augue ac dui sagittis feugiat. Morbi lobortis a massa in tincidunt. Donec viverra aliquet varius. Donec et augue vestibulum, rutrum lorem a, aliquet elit. Praesent gravida tempus justo, sed gravida erat congue eget. Morbi nisi odio, eleifend posuere eros eget, finibus eleifend ex.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla pulvinar arcu at ipsum aliquet, quis sagittis orci tristique. Aenean neque nulla, porttitor ut eleifend ut, porta ut eros. Sed tristique finibus turpis sit amet aliquam. Nam ultricies, ipsum eget varius semper, justo velit ultrices mi, eget bibendum ex odio commodo ex. Donec auctor arcu libero, pulvinar tincidunt ante tempus sit amet. Praesent et lectus interdum, consequat arcu ut, dapibus purus. Pellentesque volutpat sollicitudin venenatis. Proin ut laoreet massa. Vestibulum dapibus pharetra porta.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae odio vel ex gravida dignissim. Suspendisse potenti. Suspendisse consectetur porttitor metus, vitae consectetur metus consectetur ut. Nullam tempor tincidunt dolor, id condimentum quam commodo at. Donec a nibh sed mi porta rhoncus. Phasellus gravida, nunc a dapibus sagittis, sem justo pretium nisi, a placerat quam leo vel dui. Integer neque leo, luctus sed tellus eget, tincidunt sodales ipsum.

Quisque vehicula dolor turpis, malesuada pulvinar sem bibendum vitae. Duis justo velit, vehicula id hendrerit a, rhoncus et nibh. Nunc pharetra mattis pulvinar. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc fringilla facilisis consectetur. Nunc ultricies, mauris eu venenatis gravida, odio lacus malesuada magna, eu commodo arcu velit vitae eros. Suspendisse tincidunt in nunc et vulputate. Sed metus enim, laoreet ut dignissim sed, bibendum at magna. Sed efficitur, nulla eget vulputate aliquet, sapien erat sagittis ante, vitae lacinia ipsum nisl at ligula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra vestibulum velit, eu commodo sem convallis sed. Cras cursus arcu vestibulum, commodo risus vitae, vulputate mi. Vivamus ullamcorper ac dui vitae ornare. Integer eget varius nibh. Duis tincidunt ipsum sit amet mollis pellentesque.

Praesent dictum mattis euismod. Integer dignissim non mi vitae commodo. Sed velit enim, vehicula a libero sed, accumsan volutpat nisi. Proin dignissim tellus id sem aliquet, ut ultrices metus gravida. Vivamus quis viverra arcu, nec cursus dui. Fusce maximus dui ut tortor fringilla fermentum. Morbi quis purus mattis, efficitur libero eu, lacinia odio. Suspendisse vitae nisi at ipsum vehicula tincidunt. Nullam vitae ante vel risus facilisis commodo. Morbi viverra vitae est commodo iaculis. Etiam quis nunc eget nisi laoreet consectetur at sit amet nulla. Fusce at massa non odio ullamcorper sodales. Nulla sagittis metus eu libero maximus, non sollicitudin ex finibus. Donec laoreet consequat purus, eget semper mi feugiat in. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla non massa pharetra, vehicula erat vel, iaculis velit.

Etiam aliquam elementum diam, eget euismod sem. Cras eu facilisis turpis. Nullam sit amet laoreet est. Maecenas vel purus dapibus, tempor quam id, laoreet urna. Fusce efficitur nisi ac velit mattis sodales. Donec sagittis vel tellus ac sagittis. Sed eu velit dignissim, lacinia nisl vitae, rhoncus nulla. Pellentesque vulputate, orci sed tincidunt viverra, odio tellus ullamcorper sapien, malesuada consectetur nulla justo id nisl. Proin non magna nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam dictum nec massa id vulputate. Sed non sodales sem, sodales ornare tellus.

Aliquam sagittis, ligula sed aliquet tincidunt, augue massa venenatis odio, pellentesque venenatis sem lacus non sapien. Maecenas feugiat a lectus finibus molestie. Mauris imperdiet ullamcorper quam vitae facilisis. Phasellus molestie tellus ut commodo accumsan. Proin at tristique ex. Nulla sed magna non erat laoreet convallis ac sit amet justo. Nullam sed diam tellus. Nulla condimentum justo velit, a lobortis ex ullamcorper ut.

Donec rutrum risus eget tellus convallis, a ultrices odio hendrerit. Fusce volutpat blandit elit. Maecenas commodo dui ut maximus luctus. Aenean eu ligula leo. Donec feugiat odio est, sed suscipit odio bibendum in. Donec id risus congue, rhoncus magna in, dignissim sapien. Pellentesque nisl ante, pellentesque non erat quis, vehicula tincidunt massa. Aliquam et imperdiet lacus, nec accumsan sapien. Curabitur vitae pulvinar arcu, nec facilisis nibh. Aenean et luctus nibh, sit amet iaculis metus. Aenean elit ante, varius eget tempus ac, venenatis id urna. Fusce tincidunt velit urna, at vestibulum lacus iaculis vitae.

Aliquam quis feugiat orci. Ut neque diam, ultricies eget mi nec, faucibus sollicitudin tellus. Ut maximus justo eu neque lobortis, nec scelerisque lorem scelerisque. Nunc auctor non arcu sed ullamcorper. Nunc venenatis tincidunt magna volutpat lacinia. Fusce dignissim neque sed vehicula faucibus. Phasellus rutrum ante vel auctor iaculis.

Ut non vehicula orci. Aenean scelerisque rutrum metus ac egestas. Suspendisse potenti. Integer at nibh pulvinar, venenatis arcu et, mattis orci. Nullam arcu lectus, vehicula nec elit nec, posuere elementum purus. Ut sagittis rutrum pharetra. Mauris vitae mauris a tellus porttitor vestibulum in venenatis mi. Maecenas pretium, libero sed accumsan volutpat, mauris lacus tincidunt ante, eget ultrices tellus ante in arcu. Vivamus justo tellus, egestas id gravida non, tempor eu mauris. Praesent suscipit est et metus varius, quis posuere sem malesuada.

Fusce ultrices lobortis quam, vel sollicitudin purus imperdiet vel. Mauris dignissim in leo eget venenatis. Etiam augue sem, placerat vitae nisl sed, porta scelerisque nisl. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent rhoncus, felis id tempor tristique, quam erat finibus massa, ac egestas diam est sed nunc. Sed sem tortor, vulputate nec gravida et, tristique sit amet lorem. In ultricies blandit lorem sit amet porta. Morbi pretium quis libero ac viverra. Vivamus ultrices quis felis sit amet pellentesque. Duis ultricies augue ac dui sagittis feugiat. Morbi lobortis a massa in tincidunt. Donec viverra aliquet varius. Donec et augue vestibulum, rutrum lorem a, aliquet elit. Praesent gravida tempus justo, sed gravida erat congue eget. Morbi nisi odio, eleifend posuere eros eget, finibus eleifend ex.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla pulvinar arcu at ipsum aliquet, quis sagittis orci tristique. Aenean neque nulla, porttitor ut eleifend ut, porta ut eros. Sed tristique finibus turpis sit amet aliquam. Nam ultricies, ipsum eget varius semper, justo velit ultrices mi, eget bibendum ex odio commodo ex. Donec auctor arcu libero, pulvinar tincidunt ante tempus sit amet. Praesent et lectus interdum, consequat arcu ut, dapibus purus. Pellentesque volutpat sollicitudin venenatis. Proin ut laoreet massa. Vestibulum dapibus pharetra porta.
            </div>
        </HeaderApp>
    )
}